---
version: '3.8'

networks:
  ingress:
    driver: overlay
    external: true
    name: traefik_ingress
    labels:
      com.containous.traefikee.component: ingress-network

services:
  whoami:
    image: traefik/whoami
    environment:
      - WHOAMI_NAME=swarm
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
      placement:
        constraints:
          - node.role == worker
      labels:
        traefik.swarm.network: traefik_ingress
        traefik.http.routers.whoami.service: whoami
        traefik.http.services.whoami.loadbalancer.server.port: "80"
        traefik.http.routers.whoami.rule: Host(`whoami.localdemo.localhost`)
        traefik.http.routers.whoami.entrypoints: websecure
        traefik.http.routers.whoami.tls: "true"
    networks:
      - ingress