mode: deployment
image:
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"
  pullPolicy: IfNotPresent
presets:
  logsCollection:
    enabled: true
resources:
  limits:
    cpu: 250m
    memory: 512Mi
config:
  exporters:
    debug:
      verbosity: detailed
    otlphttp/loki:
      endpoint: http://loki.observability.svc.cluster.local:3100/otlp
    otlphttp/prom:
      endpoint: http://prometheus-stack-kube-prom-prometheus.observability.svc.cluster.local:9090/api/v1/otlp
    otlphttp/jaeg:
      endpoint: http://simplest-collector.observability.svc.cluster.local:4318
  service:
    pipelines:
      logs:
        exporters: [otlphttp/loki]
      metrics:
        exporters: [otlphttp/prom]
      traces:
        exporters: [otlphttp/jaeg] 